local bind = vim.keymap.set
local opts = { remap = true }

bind("n", "<leader>fs", ":w!<CR>", opts)
bind("n", "<leader>fed", ":e $MYVIMRC<CR>", opts)
bind("n", "<leader>feR", ":so $MYVIMRC<CR>", opts)
bind("n", "<leader>r", ":e<CR>", opts)
bind("n", "[e", "ddp", opts)
bind("n", "]e", "ddkP", opts)
bind("x", "[e", "dp", opts)
bind("x", "]e", "dkP", opts)
bind("n", "<leader>bn", ":bn<CR>", opts)
bind("n", "<leader>bp", ":bp<CR>", opts)
bind("n", "<leader>bf", ":bf<CR>", opts)
bind("n", "<leader>bx", ":%bd|e#|bd#<CR>", opts)
bind("n", "<leader>bl", ":bl<CR>", opts)
bind("n", "<leader>bd", ":bd!<CR>", opts)
bind("n", "<C-l>", "<C-w>l", opts)
bind("n", "<C-h>", "<C-w>h", opts)
bind("n", "<C-j>", "<C-w>j", opts)
bind("n", "<C-k>", "<C-w>k", opts)
bind("n", "<leader>wd", "<C-w>c", opts)
bind("n", "<leader>wc", ":on<CR>", opts)
bind("n", "<leader>qq", ":q!<CR>", opts)
bind("n", "//", ":nohlsearch<CR>", { silent = true, remap = true })
bind("n", "<C-g>", "<C-[>")
bind("n", "<leader>ff", "<cmd>Telescope find_files<cr>")
bind("n", "<leader>*", "<cmd>Telescope grep_string<cr>", opts)
bind("n", "*", "<cmd>Telescope live_grep<cr>", opts)
bind("n", "<leader>bs", "<cmd>Telescope buffers<cr>", opts)
bind("n", "/", "<cmd>Telescope current_buffer_fuzzy_find<cr>", opts)
bind("n", "gc", ":HopChar1<CR>", opts)
bind("n", "gw", ":HopWord<CR>", opts)
-- bind("n", "<leader>rtn", "<cmd>lua require('neotest').run.run()<CR>", { silent = true, remap = true })
-- bind("n", "<leader>rtf", "<cmd>lua require('neotest').run.run(vim.fn.expand('%'))<CR>", { silent = true, remap = true })
bind("t", "<C-[>", "<C-\\><C-n>", opts)
bind("n", "<leader>u", ":UndotreeToggle<CR>", { silent = true })
bind("n", "<leader>g", "<cmd>lua require('neogit').open({ kind = 'split' })<CR>")
bind("n", "<leader>rw", "<cmd>lua require('spectre').open_visual({select_word=true})<CR>")
bind("v", "<leader>rw", "<cmd>lua require('spectre').open_visual()<CR>")
bind("n", "<leader>qt", "<cmd>TroubleToggle<cr>")
bind("n", "<leader>qf", "<cmd>TroubleToggle quickfix<cr>")
bind("n", "<leader>d", "<cmd>NvimTreeToggle<cr>")
bind("n", "<leader><C-b>", "<cmd>Gitsigns toggle_current_line_blame<cr>")

bind("i", "<C-j>", function()
    return vim.fn.pumvisible() == 1 and '<C-n>' or '<C-j>'
end, { expr = true, noremap = true })
bind("c", "<C-j>", function()
    return vim.fn.pumvisible() == 1 and '<C-n>' or '<C-j>'
end, { expr = true, noremap = true })
bind("i", "<C-k>", function()
    return vim.fn.pumvisible() == 1 and '<C-p>' or '<C-k>'
end, { expr = true, noremap = true })
bind("c", "<C-k>", function()
    return vim.fn.pumvisible() == 1 and '<C-p>' or '<C-k>'
end, { expr = true, noremap = true })
