---
- name: tap emacs-plus
  homebrew_tap:
    name: d12frosted/emacs-plus
    state: present

- name: install emacs-plus
  homebrew:
    name: emacs-plus
    state: present

- name: link dotemacs config
  file:
    src: "{{ playbook_dir }}/roles/emacs-plus/files/init.el"
    dest: ~/.emacs.d/
    state: link

- name: install dracula-theme
  git:
    repo: https://github.com/dracula/emacs.git
    dest: ~/.emacs.d/themes
