---
- name: install neovim
  homebrew:
    name: neovim
    state: present

- name: create plug folder
  shell: "mkdir -p ~/.local/share/nvim/site/autoload/"

- name: create vim folder
  shell: "mkdir -p ~/.config/nvim/"

- name: vim package manager
  get_url:
    force: yes
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: ~/.local/share/nvim/site/autoload/

- name: link vim config
  file:
    src: "{{ playbook_dir }}/roles/nvim/files/vimrc"
    dest: ~/.config/nvim/init.vim
    state: link

- name: tap fonts
  homebrew_tap:
    name: caskroom/fonts
    state: present

- name: install nerd fonts
  homebrew_cask:
    name: font-hack-nerd-font
    state: present
